### ISSUE TITLE
Add Yicheng

### ISSUE THREAD

**Issue by pingsutw** [flyteorg/community#11]
## Highlighted contributions
- Flytekit timeline deck
- Flytekit runtime metric
- Real-time flyte deck
- bug fixes for the Ray plugin
- https://github.com/flyteorg/flytekit/pulls?q=is%3Apr+author%3AYicheng-Lu-llll

## What repositories do you expect to keep contributing to?
flyteadmin, flytekit, flyteidl, flyteplugins, flytepropeller

## What is the name of your current organization?
UIUC / Influxdata
## Any other context that you wish to share?
cc @Yicheng-Lu-llll

**Comment by pingsutw** [comment]
+1

**Comment by davidmirror-ops** [comment]
+1

**Comment by fg91** [comment]
+1

**Comment by fg91** [comment]
Off topic:
> Real-time flyte deck

Can we maybe use this to solve [this](https://github.com/flyteorg/flyte/discussions/3666) problem (display links to e.g. wandb which are generated at runtime in the flyte console before the task ends)?

**Comment by bstadlbauer** [comment]
+1

**Comment by davidmirror-ops** [comment]
Approved. Welcome @Yicheng-Lu-llll!
