### ISSUE TITLE
Nominate TroyChiu as core contributor

### ISSUE THREAD

**Issue by davidmirror-ops** [flyteorg/community#18]
## Highlighted contributions

**Plugin**:

- vscode plugin: https://github.com/flyteorg/flytekit/pull/1922 (done, in review)
- Improve data persistence:

- Rust: https://github.com/flyteorg/flytekit/pull/1936 (in progress)

- Python: https://github.com/flyteorg/flytekit/pull/1869 (in progress)

**Flytekit**:

- Add type transformer for datetime.date: https://github.com/flyteorg/flytekit/pull/1786 merged
- Add support for execution name prefixes: https://github.com/flyteorg/flytekit/pull/1803 merged
- add default project domain in execute launch plan: https://github.com/flyteorg/flytekit/pull/1894 merged
- Fix remote integration tests: https://github.com/flyteorg/flytekit/pull/1896 merged
- Add support for execution of reference entities: https://github.com/flyteorg/flytekit/pull/1808 done, in review
- local cache ignore portion: https://github.com/flyteorg/flytekit/pull/1914 done, in review

**Flyte**:

- Provide a way to ignore portions of the signature for cache key calculation: https://github.com/flyteorg/flyte/pull/4324 done, in review
- fix the compatibility to Mac: https://github.com/flyteorg/flyte/pull/4260 merged

**Flytesnacks**:

- add type datetime.date: https://github.com/flyteorg/flytesnacks/pull/1084 merged
- fix execution name: https://github.com/flyteorg/flytesnacks/pull/1095 merged
- add execution name prefix examples: https://github.com/flyteorg/flytesnacks/pull/1098 merged

## What repositories do you expect to keep contributing to?
- `flyte` (monorepo), `flytesnacks`

## Any other context that you wish to share?
Nominated by @ByronHsu

**Comment by ByronHsu** [comment]
Troy has been acting swiftly with high-quality results. Definitely an upvote!

**Comment by pingsutw** [comment]
+1

**Comment by fg91** [comment]
+1

**Comment by davidmirror-ops** [comment]
Approved!
