### ISSUE TITLE
Nominate Han-Ru Chen (Future-Outlier) as Flyte committer

### ISSUE THREAD

**Issue by pingsutw** [flyteorg/community#19]
[Han-Ru](https://github.com/Future-Outlier) has consistently demonstrated exceptional dedication in contributing to the Flyte project, making invaluable contributions to the community.

## Highlighted contributions
- [ChatGPT agent](https://github.com/flyteorg/flytekit/pull/1822)
- [Databricks agent](https://github.com/flyteorg/flytekit/pull/1797)
- [Sync plugin](https://github.com/flyteorg/flyte/pull/4107)
- [FlyteChatGPTSummaryBot](https://github.com/Future-Outlier/FlyteChatGPTSummaryBot)
- [Email notification](https://github.com/flyteorg/flyte/commit/029c295b04d46465f2e3d8a046b5b0aa9896ae08) in the sandbox
- Improve test coverage
    - https://github.com/flyteorg/flyte/commit/033276d42d00e508d9e66299683a5ea18efaec2f
    - https://github.com/flyteorg/flyte/commit/ac4ec7d84e88fe8a00a4b850c30a078deaee7f3e
- Added Flyte [sensor example](https://github.com/flyteorg/flyte/pull/4195).
- Added GPU enabled sandbox image
- Tons of PRs to improve the Flyte agent
- Tons of PRs to improve the Kubeflow plugin
- Flyte blog, tutorial, video.

## [Developing an LLM app with Flyte Agents](https://www.youtube.com/watch?v=IS6gi4jR7h0&ab_channel=Flyte)
[![Watch the video](https://github.com/flyteorg/community/assets/37936015/92300c43-8618-44e7-a8cc-1ce75ffca516)](https://www.youtube.com/watch?v=IS6gi4jR7h0&ab_channel=Flyte)

More detail
- https://github.com/flyteorg/flyte/commits?author=Future-Outlier
- https://github.com/flyteorg/flytekit/commits?author=Future-Outlier

## Have you been an elected Contributor for at least 6 months?
flyte (monorepo), flytesnacks

**Comment by davidmirror-ops** [comment]
+1
Long overdue :)

**Comment by ByronHsu** [comment]
+10. i assume you mean "core contributor" in the [ladder](https://github.com/davidmirror-ops/community-fork/blob/e6bbaff7ec78d58c2978317b6df5e8c5140cc134/GOVERNANCE.md). should we replace "committer" with "core contributor" to clarify the term?

**Comment by eapolinario** [comment]
+1

Thank you for all the work, @Future-Outlier. You've been an amazing contributor to Flyte. I hope we get to work a lot more in the future!

**Comment by fg91** [comment]
+1 <3

**Comment by bstadlbauer** [comment]
+1, thanks for all your contributions!

**Comment by davidmirror-ops** [comment]
Approved!
