### ISSUE TITLE
Nominating Ethan Brown (@ddl-ebrown) as Collaborator

### ISSUE THREAD

**Issue by davidmirror-ops** [flyteorg/community#21]
## Highlighted contributions

- 7 contributions merged so far, aimed at improving the security posture of a Flyte deployment and move it towards "secure by default": https://github.com/flyteorg/flyte/pulls?q=is%3Apr+is%3Aclosed+author%3Addl-ebrown
- 1 more open in the same vein and more to come!

## What repositories do you expect to keep contributing to?
- flyte
## What is the name of your current organization?
- Data Domino Labs

## Any other context that you wish to share?
- Besides the PRs, Ethan has also been willing to help other community members.

**Comment by pingsutw** [comment]
+1

**Comment by fg91** [comment]
+1

**Comment by ByronHsu** [comment]
+1

**Comment by Future-Outlier** [comment]
+1

**Comment by davidmirror-ops** [comment]
Approved!
