### ISSUE TITLE
Nominating Jason Lai (@jasonlai1218) as committer

### ISSUE THREAD

**Issue by pingsutw** [flyteorg/community#22]
## Highlighted contributions
[Jason](https://github.com/jasonlai1218) has consistently contributed to the Flyte project, making invaluable contributions to the community.

- ImageSpec imporvement
- Flyte deck improvement
- Run Jupyter Notebook inside the task
- Update and improve our official doc
- Numerous bug fixes and reports

## What repositories do you expect to keep contributing to?
- Flyte
- Flytekit

## What is the name of your current organization?
[Line](https://line.me/en/)

## Any other context that you wish to share?
Besides the PRs, Jason has also been willing to help other community members

**Comment by MortalHappiness** [comment]
+1

**Comment by austin362667** [comment]
+1

**Comment by troychiu** [comment]
Definitely +1

**Comment by ByronHsu** [comment]
+1

**Comment by davidmirror-ops** [comment]
Approved!
