### ISSUE TITLE
Nominating Tom-Newton as Committer

### ISSUE THREAD

**Issue by davidmirror-ops** [flyteorg/community#23]
## Highlighted contributions

15 (and counting) high-quality code contributions
- [flyte](https://github.com/flyteorg/flyte/pulls?q=is%3Apr+author%3Atom-newton+is%3Aclosed)
- [flytekit](https://github.com/flyteorg/flytekit/pulls?q=is%3Apr+is%3Aclosed+author%3Atom-newton)

## What repositories do you expect to keep contributing to?
- flyte, flytekit
## What is the name of your current organization?
 Wayve
## Any other context that you wish to share?
@Tom-Newton has also been diligent in reporting [Issues](https://github.com/flyteorg/flyte/issues/created_by/tom-newton) and even helping other users in the community.

**Comment by pingsutw** [comment]
+1

**Comment by Future-Outlier** [comment]
> ## Highlighted contributions
> 
> 
> 
> 15 (and counting) high-quality code contributions
> 
> - [flyte](https://github.com/flyteorg/flyte/pulls?q=is%3Apr+author%3Atom-newton+is%3Aclosed)
> 
> - [flytekit](https://github.com/flyteorg/flytekit/pulls?q=is%3Apr+is%3Aclosed+author%3Atom-newton)
> 
> 
> 
> ## What repositories do you expect to keep contributing to?
> 
> - flyte, flytekit
> 
> ## What is the name of your current organization?
> 
>  Wayve
> 
> ## Any other context that you wish to share?
> 
> @Tom-Newton has also been diligent in reporting [Issues](https://github.com/flyteorg/flyte/issues/created_by/tom-newton) and even helping other users in the community.
> 
> 

+1

**Comment by Future-Outlier** [comment]
+1

**Comment by hamersaw** [comment]
+1

**Comment by davidmirror-ops** [comment]
Approved!
