### ISSUE TITLE
Nominating Rafael Raposo for Collaborator role

### ISSUE THREAD

**Issue by davidmirror-ops** [flyteorg/community#24]
## Highlighted contributions

- `GetProject` endpoint in FlyteAdmin: https://github.com/flyteorg/flyte/pull/4825
- ExecutionClusterLabels https://github.com/flyteorg/flyte/pull/4998
- Preserv stack trace in flytekit: https://github.com/flyteorg/flytekit/pull/2056

## What repositories do you expect to keep contributing to?
- flyte
- flytekit
## What is the name of your current organization?
- Spotify
## Any other context that you wish to share?
@RRap0so has also been active on the Contributor's meetups, and their contributions reflect a real interest on improving DX for Flyte users.

**Comment by pingsutw** [comment]
+1

**Comment by Future-Outlier** [comment]
> ## Highlighted contributions
> 
> 
> 
> - `GetProject` endpoint in FlyteAdmin: https://github.com/flyteorg/flyte/pull/4825
> 
> - ExecutionClusterLabels https://github.com/flyteorg/flyte/pull/4998
> 
> - Preserv stack trace in flytekit: https://github.com/flyteorg/flytekit/pull/2056
> 
> 
> 
> ## What repositories do you expect to keep contributing to?
> 
> - flyte
> 
> - flytekit
> 
> ## What is the name of your current organization?
> 
> - Spotify
> 
> ## Any other context that you wish to share?
> 
> @RRap0so has also been active on the Contributor's meetups, and their contributions reflect a real interest on improving DX for Flyte users.
> 
> 

+1

**Comment by Future-Outlier** [comment]
+1

**Comment by davidmirror-ops** [comment]
Approved!
