### ISSUE TITLE
Nominating Rafael Raposo for TSC

### ISSUE THREAD

**Issue by davidmirror-ops** [flyteorg/community#25]
## Highlighted contributions

- Multiple [contributions](https://github.com/flyteorg/flyte/pulls?q=is%3Apr+author%3ARRap0so+is%3Aclosed) including going through the entire RFC process until implementation.
- Rafael has been active in the community and is part of an organization that's been a  Flyte supporter for a long time.

## What repositories do you expect to keep contributing to?
- flyte, flytekit
## What is the name of your current organization?
- Spotify
## Any other context that you wish to share?

See [GOVERNANCE](https://github.com/flyteorg/community/blob/main/GOVERNANCE.md) for additional context and expectations.

**Comment by davidmirror-ops** [comment]
cc @fg91 @pingsutw @eapolinario

**Comment by pingsutw** [comment]
+1

**Comment by davidmirror-ops** [comment]
Thanks. Approved!

**Comment by fg91** [comment]
+1
