### ISSUE TITLE
Promote Jason Parraga to Committer

### ISSUE THREAD

**Issue by davidmirror-ops** [flyteorg/community#27]
## Highlighted contributions

- Multiple [contributions](https://github.com/flyteorg/flyte/pulls?q=is%3Apr+author%3Asovietaced+is%3Aclosed) on docs, Helm charts, security, and other fronts.
- Jason has also been striving to help other community members with questions

## What repositories do you expect to keep contributing to?
- flyte
## What is the name of your current organization?
- StackAV

**Comment by pingsutw** [comment]
+1

**Comment by Future-Outlier** [comment]
He's been consistently contributing to Flyte.
He definitely deserves a committer badge!

**Comment by RRap0so** [comment]
+1 👏

**Comment by fg91** [comment]
+1

**Comment by davidmirror-ops** [comment]
Approved!
