### ISSUE TITLE
Nominate Howard Wang (novahow) as Flyte committer

### ISSUE THREAD

**Issue by Future-Outlier** [flyteorg/community#29]
[Howard](https://github.com/novahow) has consistently contributed to flyte and flytekit.
He developed many different features and solved numerous existing problems.
He is self-taught in many aspects of Flyte and he is a really good contributor that
I would even want to keep collaborating with him.

#### flytekit
- [skypilot agent](https://github.com/flyteorg/flytekit/pull/2407)
- [Show version and execute by version](https://github.com/flyteorg/flytekit/pull/2124)
- [Support torch async dist checkpoint](https://github.com/flyteorg/flytekit/pull/2612)
- [Core/fix register remote](https://github.com/flyteorg/flytekit/pull/2303)
- [Support async workflow & task](https://github.com/flyteorg/flytekit/pull/2611)
#### flytekit
- [fix datetime in eager workflow](https://github.com/flyteorg/flytekit/pull/2541)
- [Core/enable deck](https://github.com/flyteorg/flytekit/pull/2314)
- [Core/cli recover](https://github.com/flyteorg/flytekit/pull/2294)
- [fix limit option](https://github.com/flyteorg/flytekit/pull/2292)
- [try removing multiple imports to resolve fast-mode issue](https://github.com/flyteorg/flytekit/pull/2110)
#### flyte
- [reimplement functions in go-mouff-update, use ghreposervice](https://github.com/flyteorg/flyte/pull/5470)
- [fix make link error](https://github.com/flyteorg/flyte/pull/5175)
- [add plugins support for k8s imagepullpolicy](https://github.com/flyteorg/flyte/pull/5167)
- [add hostname to input](https://github.com/flyteorg/flyte/pull/4939)

## What repositories do you expect to keep contributing to?
flyte and flytekit
## What is the name of your current organization?
Georgia Tech

**Comment by pingsutw** [comment]
+1

**Comment by davidmirror-ops** [comment]
+1
Thank you @Future-Outlier

**Comment by ByronHsu** [comment]
+1

**Comment by austin362667** [comment]
+1

**Comment by MortalHappiness** [comment]
+1

**Comment by Mecoli1219** [comment]
+1

**Comment by troychiu** [comment]
+1
