### ISSUE TITLE
Add byronhsu

### ISSUE THREAD

**Issue by wild-endeavor** [flyteorg/community#9]
## Highlighted contributions
Just a sample: https://github.com/flyteorg/flyte/issues/3620

## What repositories do you expect to keep contributing to?
flyteadmin, flytekit, flyteidl, flyteplugins, flytepropeller

## What is the name of your current organization?
LinkedIn.

**Comment by pingsutw** [comment]
+1

**Comment by davidmirror-ops** [comment]
Completed
